"""Public API for ConvRot MLX."""

from .core import (
    CONVROT_GROUP_SIZE,
    INT4_MAX,
    SUPPORTED_BACKENDS,
    SUPPORTED_FUSED_GROUP_SIZES,
    SUPPORTED_PREPROCESSORS,
    ConvRotLinear,
    compiled_prepare_convrot_activation,
    compiled_regular_hadamard,
    eligible_linear,
    expanded_fp32_w4a4_matmul,
    metal_fused_prepare_convrot_activation,
    metal_fused_prepare_convrot_activation_i8,
    metal_fused_rotate_convrot_activation,
    metal_unpack_signed_int4,
    mpp_w4a4_int8_matmul,
    mpp_w4a4_matmul,
    mpp_w4a16_matmul,
    pack_signed_int4,
    packed_w4a4_matmul,
    packed_w4a4_matmul_k32,
    packed_w4a4_matmul_k64,
    packed_w4a4_matmul_k128,
    packed_w4a4_matmul_k256,
    packed_w4a4_matmul_m16n64_k64,
    packed_w4a4_matmul_m32n32_k64,
    prepare_convrot_activation,
    quantize_convrot_weight,
    quantize_signed_int4_rowwise,
    reference_w4a4_matmul,
    regular_hadamard,
    repack_mpp_weight_to_nk,
    repack_nk_weight_for_mpp,
    unpack_signed_int4,
)

__version__ = "0.1.0"

__all__ = [
    "CONVROT_GROUP_SIZE",
    "INT4_MAX",
    "SUPPORTED_BACKENDS",
    "SUPPORTED_FUSED_GROUP_SIZES",
    "SUPPORTED_PREPROCESSORS",
    "ConvRotLinear",
    "compiled_prepare_convrot_activation",
    "compiled_regular_hadamard",
    "eligible_linear",
    "expanded_fp32_w4a4_matmul",
    "metal_fused_prepare_convrot_activation",
    "metal_fused_prepare_convrot_activation_i8",
    "metal_fused_rotate_convrot_activation",
    "metal_unpack_signed_int4",
    "mpp_w4a4_int8_matmul",
    "mpp_w4a4_matmul",
    "mpp_w4a16_matmul",
    "pack_signed_int4",
    "packed_w4a4_matmul",
    "packed_w4a4_matmul_k32",
    "packed_w4a4_matmul_k64",
    "packed_w4a4_matmul_k128",
    "packed_w4a4_matmul_k256",
    "packed_w4a4_matmul_m16n64_k64",
    "packed_w4a4_matmul_m32n32_k64",
    "prepare_convrot_activation",
    "quantize_convrot_weight",
    "quantize_signed_int4_rowwise",
    "reference_w4a4_matmul",
    "regular_hadamard",
    "repack_mpp_weight_to_nk",
    "repack_nk_weight_for_mpp",
    "unpack_signed_int4",
]
